apiVersion: v1
kind: Pod
metadata:
  name: demo
  namespace: esp
spec:
  containers:
  - env:
    - name: ESPENV_meta_meteringcontext
      value: eventStreamProcessing/v1
    - name: ESPENV_meta_meteringhost
      value: http://sas-event-stream-processing-metering-app
    - name: ESPENV_meta_meteringport
      value: "80"
    - name: ESPENV_server_store-location
      value: /mnt/data
    - name: ESP_MEM_LIMIT_MIB
      value: "2048"
    - name: MAS_M2PATH
      value: /opt/sas/viya/home/SASFoundation/misc/embscoreeng/mas2py.py
    - name: MAS_PYPATH
      value: /usr/bin/python3
    - name: ESP_PROJECT_OUTPUT
      value: "/mnt/data/output"
    image: espscr.azurecr.io/sas-esp-cr-apps/modelreader_onnx_yolov4_cpu_1-x86_64:latest
    imagePullPolicy: IfNotPresent
    name: demo
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: "2"
        memory: 1Gi
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsGroup: 1001
      runAsNonRoot: true
      runAsUser: 1001
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /mnt/data
      name: data
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  imagePullSecrets:
  - name: acrpub-secret
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    seccompProfile:
      type: RuntimeDefault
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: esp-pv
